x = input('Digite algo: ')
print(f'O tipo primitvo desse valor é {type(x)}')
print(f'É alfa numérico? {x.isalnum()}')
print(f'É alfabético? {x.isalpha()}')
print(f'É um número? {x.isnumeric()}')
print(f'É escrito em liguage m hexadecimal? {x.isascii()}')
print(f'É um digito? {x.isdigit()}')
print(f'É um número decimal? {x.isdecimal()}')
print(f'É um identificador válido? {x.isidentifier()}')
print(f'É minúsculo? {x.islower()}')
print(f'É espaço? {x.isspace()}')
print(f'É possivel excrever na tela? {x.isprintable()}')
print(f'É um titulo? {x.istitle()}')
print(f'É maiscula? {x.isupper()}')