x = input('Digite algo: ')
print('É alfa numérico? ',x.isalnum())
print('É alfabeto? ',x.isalpha())
print('É um número? ',x.isnumeric())
print('É escrito em liguagem hexadecimal? ',x.isascii())
print('É um digito? ',x.isdigit())
print('É um número decimal? ',x.isdecimal())
print('É um identificador válido? ',x.isidentifier())
print('É minúsculo',x.islower())
print('É espaço? ',x.isspace())
print('É possivel excrever na tela? ',x.isprintable())
print('É um titulo? ',x.istitle())
print('É maiscula? ',x.isupper())